### PR TITLE
fix(nimble-data-table): ability to hide Main action button

### LINKED ISSUE #189: Nimble Data Table: Add props for hiding main action button
hide-main-action-button

Current: there is not an option for hiding the main button via props.

Required: ability to hide this main action button via Boolean props

### PR DESCRIPTION
**Pull request by anuja01**
Show main action button only if there's a main action callback

fix #189

### CODE REVIEW

File: src/components/nimbleDataTable/NimbleDataTable.tsx [hunk 1]
```diff
@@ -153,12 +153,12 @@ export const NimbleDataTable: React.FC<NimbleDataTableProps> = ({
   const filterChangeDebounceHandler = useMemo(() => debounce(handleFilterChange, 500), [filterData]);
 
   const handleClicShort = (sortKey: string | undefined, sortOrder: string): void => {
-      if (sortKey) {
-        onClickSort && onClickSort(sortKey, sortOrder);
-        setSortData({
-          ...(isEnableMultipleSort ? sortData : {}),
-          [sortKey]: sortOrder,
-        });
+    if (sortKey) {
```
Comment (anuja01) [inline src/components/nimbleDataTable/NimbleDataTable.tsx:156]: this is just formatting

**Review by Manoj201 — APPROVED** [review]
