### PR TITLE
fix(nimble-data-table): fix font family and font size for search filters

### LINKED ISSUE #245: Allow modifying placeholder text font family in Nimble data table
Placeholder-fonts

**Current**
The current font family prop does not apply to the search and filter placeholder text.

**Required**
prop for targeting font family of search and filter placeholder text in nimble data table

### PR DESCRIPTION
**Pull request by anuja01**
fix #245

### CODE REVIEW

File: src/components/nimbleDataTable/FilterInputItem.tsx [hunk 1]
```diff
@@ -41,10 +41,11 @@ const FilterInputItem: React.FC<FilterInputItemProps> = ({item, filterChangeDebo
               <NimbleSelect
                 data={generateFilterSelection(item.customFilterSelections, item.dataPoint)}
                 height="30px"
-                fontSize={11}
```
Comment (anuja01) [inline src/components/nimbleDataTable/FilterInputItem.tsx:44]: I've checked Figma for all projects; this is the standard size in Figma.

**Review by Manoj201 — APPROVED** [review]
