### PR TITLE
fix(nimble-file-upload): Multiple bug fixes

### LINKED ISSUE #211: Too much padding in file uploader
too-much-padding

Current - too much padding in the horizontal lane of the button to upload

Required - some prop to change the central space area in the upload component of the design system

### LINKED ISSUE #214: nimble file uploader not allowing re-upload of file
**Problem**: 
I have a nimble file uploader that is being used to allow one file upload - whenever there is one file uploaded, it will automatically hide the display of the "upload file" button. 

when a file is uploaded with the "upload files" button and then immediately deleted, and then the same file is selected for upload, the uploader doesn't run the "onFileSelect" function, and the logic to parse the upload doesn't trigger.

**Expected**:
be able to run the "onFileSelect" function again when the same file that was uploaded before is uploaded.

### LINKED ISSUE #229: separate font family for file uploader button
**Currently:**
The prop "fontFamily" in file uploader button applies the same font for the entire component, including the button.

different-font-family-needed-for-button

**Required**
New prop to target font family for the file uploader button separate from the other text content.

### PR DESCRIPTION
**Pull request by anuja01**
fix #214 
fix #211 
fix #229

### CODE REVIEW

File: src/components/nimbleFileUploader/NimbleFileUploader.tsx [hunk 1]
```diff
@@ -123,22 +125,22 @@ export const NimbleFileUploader: React.FC<NimbleFileUploaderProps> = ({
   return (
     <Container width={width} height={height}>
       <TopWrapper>
+        <HeaderText color={headerFontColor} fontFamily={fontFamily}>
```
Comment (anuja01) [inline src/components/nimbleFileUploader/NimbleFileUploader.tsx:128]: Header is moved here to align with the upload button

File: src/components/nimbleFileUploader/NimbleFileUploader.tsx [hunk 2]
```diff
@@ -80,14 +82,14 @@ export const NimbleFileUploader: React.FC<NimbleFileUploaderProps> = ({
...
     const selectedFile = event.target.files[0];
     if (selectedFile) {
-      console.log(selectedFile);
       const fileName = selectedFile.name;
       const fileSize = Math.round(selectedFile.size / 1024);
       // const extension = fileName.substring(fileName.lastIndexOf('.') + 1);
 
       const data = await toBase64(selectedFile);
       onFileSelect(fileName, data, fileSize + 'KB', fileIdForEdit);
     }
```
Comment (anuja01) [inline src/components/nimbleFileUploader/NimbleFileUploader.tsx:91]: If the value is not cleared, the `onChange` event will not trigger if the user tries to upload the same file again.

**Review by Manoj201 — APPROVED** [review]
