### PR TITLE
fix(nimble autocomplete): autocomplete search behind chip

### LINKED ISSUE #72: Autocomplete search behind chip when enough space left
Schermafbeelding 2023-08-04 om 13 15 37

### PR DESCRIPTION
**Pull request by anuja01**
Autocomplete search behind chip when enough space left
Screenshot 2023-10-12 at 10 47 44 AM

fix #72

### CODE REVIEW

**Comment by anuja01** [comment]
Screenshot 2023-10-12 at 10 47 44 AM

File: src/components/nimbleAutoComplete/StyledWrappers.tsx [hunk 1]
```diff
@@ -67,7 +61,8 @@ const SlectedIcon = styled(CheckCircleOutlineIcon)(({chipcolor}: SlectedIconProp
 }));
 
 const TextInput = styled(TextField)(({fontFamily}: TextInputProps) => ({
+  '& input': {minWidth: '75px !important'},
```
Comment (anuja01) [inline src/components/nimbleAutoComplete/StyledWrappers.tsx:64]: THis is to make sure that "input search" move to new line if it doesn't have enough space(otherwise it'll just show part of the text hidden and it doesn't look good)

**Review by Manoj201 — APPROVED** [review]
